name: app_media
description: Simple media app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.5.3
  intl: ^0.18.0

dev_dependencies:
  dart_code_metrics: ^5.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/video/sample.mp4
